version: '3.9'

networks:
  perunanetti:

services:
  # Database for the application
  postgres:
    image: postgres:14.1
    networks:
      - perunanetti
    volumes:
      - ./res/docker_mounts/:/var/lib/postgres/data
      - ./res/data.sql/:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The application, includes the API and Client
  application:
    image: chocoapp:1.0
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - perunanetti
    depends_on:
      - postgres
