version: 2.1

jobs: 
  build:
    # docker dependency
    docker:
      - image: node:16.15.1-alpine3.15
    # the actual build
    npm-deploy:
      steps:
        - checkout
        - run: 
            name: test node version
            command: node --version
        - run: 
            name: install api dependencies
            command: npm install
        - run: 
            name: build the api to /dist
            command: npm run build
        - run: 
            name: run the tests
            command: npm run test
        - run: 
            name: Run the the client
            command: npm run start:prod

workflows:
  deploy:
    jobs:
      - build
